name: Despierta Streamlit
on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta todos los días a las 00:00 UTC
  workflow_dispatch:      # Permite ejecución manual

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -I https://miaa-sincronizador-version-app.streamlit.app
